---
driver:
  name: vagrant

client_rb:
  treat_deprecation_warnings_as_errors: true
  resource_cloning: false

provisioner:
  name: chef_zero

platforms:
  - name: fileutils-centos
    require_chef_omnibus: 14.10.9
    driver_config:
      box: opscode-centos-7.2
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2_chef-provisionerless.box

  - name: ubuntu-16.04
    require_chef_omnibus: 14.10.9

suites:
  - name: default
    run_list:
      - recipe[testutils]
    attributes:
