<% proxy_vars = {} %>
<% %w(http_proxy https_proxy no_proxy).each do |envvar| %>
<%   if ENV.key?(envvar) %>
<%     proxy_vars[envvar] = ENV[envvar] %>
<%   end %>
<% end %>
---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: 12.19.36
<% if proxy_vars.size > 0 %>
<% %w(http_proxy https_proxy no_proxy).each do |envvar| %>
<% if ENV.key?(envvar) %>
  <%= envvar %>: '<%= ENV[envvar] %>'
<% end %>
<% end %>
<% end %>

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[testutils]
    attributes:
